# Generated by Django 6.0.5 on 2026-05-19 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_appointment_type_and_more'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_type', models.CharField(choices=[('general', 'General Consultation'), ('followup', 'Follow-up'), ('emergency', 'Emergency'), ('dressing', 'Dressing'), ('injection', 'Injection'), ('bp_check', 'BP Check'), ('prescription', 'Prescription Pickup'), ('counseling', 'Drug Counseling'), ('blood_test', 'Blood Test'), ('urine_test', 'Urine Test'), ('culture', 'Culture'), ('other', 'Other Test'), ('xray', 'X-Ray'), ('mri', 'MRI'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('assessment', 'Initial Assessment'), ('treatment', 'Treatment Session'), ('review', 'Review'), ('checkup', 'Checkup'), ('cleaning', 'Cleaning'), ('extraction', 'Extraction'), ('root_canal', 'Root Canal'), ('filling', 'Filling'), ('preop', 'Pre-op Consultation'), ('postop', 'Post-op Review'), ('preop_assessment', 'Pre-op Assessment'), ('postop_review', 'Post-op Review'), ('initial', 'Initial Consultation'), ('diet_review', 'Diet Review')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('break', 'Break'), ('completed', 'Completed')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot', to='appointments.appointment')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('staff', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '1 hour'), (90, '1.5 hours'), (120, '2 hours')], default=30)),
                ('max_patients', models.IntegerField(default=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('staff', 'day')},
            },
        ),
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.TimeField()),
                ('break_end', models.TimeField()),
                ('label', models.CharField(default='Break', help_text='e.g. Lunch, Prayer, Rest', max_length=50)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='schedules.staffavailability')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
