# Generated by Django 6.0.5 on 2026-05-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_date_of_birth_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab_scientist', 'Laboratory Scientist'), ('radiologist', 'Radiologist'), ('physiotherapist', 'Physiotherapist'), ('dentist', 'Dentist'), ('surgeon', 'Surgeon'), ('anesthetist', 'Anesthetist'), ('dietitian', 'Dietitian'), ('receptionist', 'Receptionist'), ('admin_staff', 'Administrative Staff'), ('it_staff', 'IT Staff'), ('manager', 'Manager'), ('admin', 'Admin')], default='patient', max_length=20),
        ),
    ]
