# Generated by Django 6.0.5 on 2026-05-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_notifications_user_notify_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notify_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_appointments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_meetings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_schedules',
        ),
    ]
